INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 
        'Test',
        'User',
        'joel@joelburton.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'joel@joelburton.com',
        TRUE);

INSERT INTO products (id,
                      title,
                      description,
                      price,
                      discountPercentage,
                      rating,
                      stock,
                      brand,
                      category,
                      thumbnail)
VALUES (1, 'iPhone 9', 'An apple mobile which is nothing like apple',  
        549, 12.96, 4.69, 94, 'Apple', 'smartphones',  
        '/images/thumbnail/thumbnail_1.jpg'),
        (2, 'iPhone X', 'SIM-Free,  Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...', 
        899, 17.94, 4.44, 34, 'Apple', 'smartphones', 
        '/images/thumbnail/thumbnail_2.jpg'), 
        (3, 'Samsung Universe 9', 'Samsung new variant which goes beyond Galaxy to the Universe', 
        1249, 15.46, 4.09, 36, 'Samsung', 'smartphones', 
        '/images/thumbnail/thumbnail_3.jpg'), 
        (4, 'OPPOF19', 'OPPO F19 is officially announced on April 2021.', 
        280, 17.91, 4.3, 123, 'OPPO', 'smartphones', 
        '/images/thumbnail/thumbnail_4.jpg'), 
        (5, 'Huawei P30', 'Huaweis re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.', 
        499, 10.58, 4.09, 32, 'Huawei', 'smartphones', 
        '/images/thumbnail/thumbnail_5.jpg'), 
        (6, 'MacBook Pro', 'MacBook Pro 2021 with mini-LED display may launch between September,  November', 
        1749, 11.02, 4.57, 83, 'Apple', 'laptops', 
        '/images/thumbnail/thumbnail_6.png'), 
        (7, 'Samsung Galaxy Book', 'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip,  8GB of RAM Launched', 
        1499, 4.15, 4.25, 50, 'Samsung', 'laptops', 
        '/images/thumbnail/thumbnail_7.jpg'), 
        (8, 'Microsoft Surface Laptop 4', 'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.', 
        1499, 10.23, 4.43, 68, 'Microsoft Surface', 'laptops', 
        '/images/thumbnail/thumbnail_8.jpg'), 
        (9, 'Infinix INBOOK', 'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey 1 Year Warranty', 
        1099, 11.83, 4.54, 96, 'Infinix', 'laptops', 
        '/images/thumbnail/thumbnail_9.jpg'), 
        (10, 'HP Pavilion 15-DK1056WM', 'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5,  8GB,  256GB SSD,  GTX 1650 4GB,  Windows 10', 
        1099, 6.18, 4.43, 89, 'HP Pavilion', 'laptops', 
        '/images/thumbnail/thumbnail_10.jpeg'), 
        (11, 'perfume Oil', 'Mega Discount,  Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil', 
        13, 8.4, 4.26, 65, 'Impression of Acqua Di Gio', 'fragrances', 
        '/images/thumbnail/thumbnail_11.jpg'), 
        (12, 'Brown Perfume', 'Royal_Mirage Sport Brown Perfume for Men & Women - 120ml', 
        40, 15.66, 4, 52, 'Royal_Mirage', 'fragrances', 
        '/images/thumbnail/thumbnail_12.jpg'), 
        (13, 'Fog Scent Xpressio Perfume', 'Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men', 
        13, 8.14, 4.59, 61, 'Fog Scent Xpressio', 'fragrances', 
        '/images/thumbnail/thumbnail_13.png'), 
        (14, 'Non-Alcoholic Concentrated Perfume Oil', 'Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil', 
        120, 15.6, 4.21, 114, 'Al Munakh', 'fragrances', 
        '/images/thumbnail/thumbnail_14.jpg'), 
        (15, 'Eau De Perfume Spray', 'Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality', 
        30, 10.99, 4.7, 105, 'Lord - Al-Rehab', 'fragrances', 
        '/images/thumbnail/thumbnail_15.jpg'), 
        (16, 'Hyaluronic Acid Serum', 'LOreal Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid', 
        19, 13.31, 4.83, 110, 'LOreal Paris', 'skincare', 
        '/images/thumbnail/thumbnail_16.jpg'), 
        (17, 'Tree Oil 30ml', 'Tea tree oil contains a number of compounds,  including terpinen-4-ol,  that have been shown to kill certain bacteria, ', 
        12, 4.09, 4.52, 78, 'Hemani Tea', 'skincare', 
        '/images/thumbnail/thumbnail_17.jpg'), 
        (18, 'Oil Free Moisturizer 100ml', 'Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides,  hyaluronic acid & sunscreen.', 
        40, 13.1, 4.56, 88, 'Dermive', 'skincare', 
        '/images/thumbnail/thumbnail_18.jpg'), 
        (19, 'Skin Beauty Serum.', 'Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m',
        46, 10.68, 4.42, 54, 'ROREC White Rice', 'skincare', 
        '/images/thumbnail/thumbnail_19.jpg'), 
        (20, 'Freckle Treatment Cream- 15gm', 'Fair & Clear is Pakistan only pure Freckle cream which helpsfade Freckles,  Darkspots and pigments. Mercury level is 0%,  so there are no side effects.', 
        70, 16.99, 4.06, 140, 'Fair & Clear', 'skincare', 
        '/images/thumbnail/thumbnail_20.jpg'), 
        (21, '- Daal Masoor 500 grams', 'Fine quality Branded Product Keep in a cool and dry place', 
        20, 4.81, 4.44, 133, 'Saaf & Khaas', 'groceries', 
        '/images/thumbnail/thumbnail_21.png'), 
        (22, 'Elbow Macaroni - 400 gm', 'Product details of Bake Parlor Big Elbow Macaroni - 400 gm', 
        14, 15.58, 4.57, 146, 'Bake Parlor Big', 'groceries', 
        '/images/thumbnail/thumbnail_22.jpg'), 
        (23, 'Orange Essence Food Flavou', 'Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item',
        14, 8.04, 4.85, 26, 'Baking Food Items', 'groceries', 
        '/images/thumbnail/thumbnail_23.jpg'), 
        (24, 'cereals muesli fruit nuts', 'original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji', 
        46, 16.8, 4.94, 113, 'fauji', 'groceries', 
        '/images/thumbnail/thumbnail_24.jpg'), 
        (25, 'Gulab Powder 50 Gram', 'Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds', 
        70, 13.58, 4.87, 47, 'Dry Rose', 'groceries', 
        '/images/thumbnail/thumbnail_25.jpg'), 
        (26, 'Plant Hanger For Home', 'Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf', 
        41, 17.86, 4.08, 131, 'Boho Decor', 'home-decoration', 
        '/images/thumbnail/thumbnail_26.jpg'), 
        (27, 'Flying Wooden Bird', 'Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF,  Laminated 3.5mm', 
        51, 15.58, 4.41, 17, 'Flying Wooden', 'home-decoration', 
        '/images/thumbnail/thumbnail_27.png'), 
        (28, '3D Embellishment Art Lamp', '3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)', 
        20, 16.49, 4.82, 54, 'LED Lights', 'home-decoration', 
        '/images/thumbnail/thumbnail_28.jpg'), 
        (29, 'Handcraft Chinese style', 'Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate', 
        60, 15.34, 4.44, 7, 'luxury palace', 'home-decoration', 
        '/images/thumbnail/thumbnail_29.png'), 
        (30, 'Key Holder', 'Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality', 
        30, 2.92, 4.92, 54, 'Golden', 'home-decoration', 
        '/images/thumbnail/thumbnail_30.jpg');

INSERT INTO images (id, image_url) 
VALUES (1, '/images/products/product1_1.jpg'), 
        (1, '/images/products/product1_2.jpg'), 
        (1, '/images/products/product1_3.jpg'), 
        (2, '/images/products/product2_1.jpg'), 
        (2, '/images/products/product2_2.jpg'), 
        (2, '/images/products/product2_3.jpg'), 
        (2, '/images/products/product2_4.jpg'),
        (3, '/images/products/product3_1.jpg'),
        (4, '/images/products/product4_1.jpg'), 
        (4, '/images/products/product4_2.jpg'), 
        (4, '/images/products/product4_3.jpg'),
        (4, '/images/products/product4_4.jpg'), 
        (4, '/images/products/product4_5.jpg'),
        (5, '/images/products/product5_1.jpg'), 
        (5, '/images/products/product5_2.jpg'), 
        (5, '/images/products/product5_3.jpg'),
        (6, '/images/products/product6_1.png'), 
        (6, '/images/products/product6_2.jpg'), 
        (6, '/images/products/product6_3.png'),
        (6, '/images/products/product6_4.jpg'),
        (7, '/images/products/product7_1.jpg'),
        (7, '/images/products/product7_2.jpg'), 
        (7, '/images/products/product7_3.jpg'), 
        (7, '/images/products/product7_4.jpg'),
        (8, '/images/products/product8_1.jpg'),
        (8, '/images/products/product8_2.jpg'),
        (8, '/images/products/product8_3.jpg'),
        (8, '/images/products/product8_4.jpg'),
        (8, '/images/products/product8_5.jpg'),
        (9, '/images/products/product9_1.jpg'),
        (9, '/images/products/product9_2.png'),
        (9, '/images/products/product9_3.png'),
        (9, '/images/products/product9_4.jpg'),
        (9, '/images/products/product9_5.jpg'),
        (10, '/images/products/product10_1.jpg'), 
        (10, '/images/products/product10_2.jpg'),
        (10, '/images/products/product10.3.jpg'),
        (10, '/images/products/product10_4.jpeg'),
        (11, '/images/products/product11_1.jpg'),
        (11, '/images/products/product11_2.jpg'),
        (11, '/images/products/product11_3.jpg'), 
        (11, '/images/products/product11_4.jpg'),
        (12, '/images/products/product12_1.jpg'),
        (12, '/images/products/product12_2.jpg'),
        (12, '/images/products/product12_3.png'),
        (12, '/images/products/product12_4.jpg'),
        (12, '/images/products/product12_5.jpg'),
        (13, '/images/products/product13_1.jpg'),
        (13, '/images/products/product13_2.png'),
        (13, '/images/products/product13_3.jpg'),
        (13, '/images/products/product13_4.jpg'),
        (13, '/images/products/product13_5.png'),
        (14, '/images/products/product14_1.jpg'),
        (14, '/images/products/product14_2.jpg'),
        (14, '/images/products/product14_3.jpg'),
        (14, '/images/products/product14_4.jpg'),
        (15, '/images/products/product15_1.jpg'),
        (15, '/images/products/product15_2.jpg'),
        (15, '/images/products/product15_3.jpg'),
        (15, '/images/products/product15_4.jpg'),
        (15, '/images/products/product15_5.jpg'),
        (16, '/images/products/product16_1.png'),
        (16, '/images/products/product16_2.png'),
        (16, '/images/products/product16_3.jpg'),
        (16, '/images/products/product16_4.jpg'),
        (16, '/images/products/product16_5.jpg'),
        (17, '/images/products/product17_1.jpg'),
        (17, '/images/products/product17_2.jpg'),
        (17, '/images/products/product17_3.jpg'),
        (17, '/images/products/product17_4.jpg'),
        (18, '/images/products/product18_1.jpg'),
        (18, '/images/products/product18_2.jpg'),
        (18, '/images/products/product18_3.jpg'),
        (18, '/images/products/product18_4.jpg'),
        (18, '/images/products/product18_5.jpg'),
        (19, '/images/products/product19_1.jpg'),
        (19, '/images/products/product19_2.jpg'),
        (19, '/images/products/product19_3.png'),
        (19, '/images/products/product19_4.jpg'),
        (20, '/images/products/product20_1.jpg'),
        (20, '/images/products/product20_2.jpg'),
        (20, '/images/products/product20_3.jpg'),
        (21, '/images/products/product21_1.png'),
        (21, '/images/products/product21_2.jpg'),
        (21, '/images/products/product21_3.jpg'),
        (22, '/images/products/product22_1.jpg'),
        (22, '/images/products/product22_2.jpg'),
        (22, '/images/products/product22_3.jpg'),
        (23, '/images/products/product23_1.jpg'),
        (23, '/images/products/product23_2.jpg'),
        (23, '/images/products/product23_3.jpg'),
        (23, '/images/products/product23_4.jpg'),
        (23, '/images/products/product23_5.jpg'),
        (24, '/images/products/product24_1.jpg'),
        (24, '/images/products/product24_2.jpg'),
        (24, '/images/products/product24_3.jpg'),
        (24, '/images/products/product24_4.jpg'),
        (24, '/images/products/product24_5.jpg'),
        (25, '/images/products/product25_1.png'),
        (25, '/images/products/product25_2.jpg'),
        (25, '/images/products/product25_3.png'),
        (25, '/images/products/product25_4.jpg'),
        (25, '/images/products/product25_5.jpg'),
        (26, '/images/products/product26_1.jpg'),
        (26, '/images/products/product26_2.jpg'),
        (26, '/images/products/product26_3.jpg'),
        (26, '/images/products/product26_4.jpg'), 
        (26, '/images/products/product26_5.jpg'),
        (26, '/images/products/product26_6.jpg'),
        (27, '/images/products/product27_1.jpg'),
        (27, '/images/products/product27_2.jpg'),
        (27, '/images/products/product27_3.jpg'),
        (27, '/images/products/product27_4.jpg'),
        (27, '/images/products/product27_5.png'),
        (28, '/images/products/product28_1.jpg'),
        (28, '/images/products/product28_2.jpg'),
        (28, '/images/products/product28_3.png'),
        (28, '/images/products/product28_4.jpg'),
        (28, '/images/products/product28_5.jpg'),
        (29, '/images/products/product29_1.jpg'),
        (29, '/images/products/product29_1.jpg'),
        (29, '/images/products/product29_3.png'),
        (29, '/images/products/product29_4.png'),
        (29, '/images/products/product29_5.png'),
        (30, '/images/products/product30_1.jpg'),
        (30, '/images/products/product30_2.jpg'),
        (30, '/images/products/product30_3.jpg'),
        (30, '/images/products/product30_4.jpg');